version: '3'

services:
  frontend:
    build:
      context: ./Obligatorio_BDD_Frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./Obligatorio_BDD_Backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: nDdjoPc45tze8OCvE03a
      MYSQL_DATABASE: burqmmbomj1nmp4a7xce
      MYSQL_USER: u4vgtbejqvsjt5uh
      MYSQL_PASSWORD: nDdjoPc45tze8OCvE03a
    ports:
      - "3306:3306"